name: Review
on: [pull_request]
jobs:
  reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: Update
      run: sudo apt-get update

    - name: Setup Lua
      run: sudo apt-get install -y lua5.1 liblua5.1-0-dev

    - name: Setup Luacheck
      run: sudo apt-get install -y lua-check

    - name: Setup xmllint
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils

    - name: Setup cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Check out code.
      uses: actions/checkout@v1

    - name: Setup reviewdog
      run: |
        mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin

    - name: cpplint
      uses: reviewdog/action-cpplint@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-check
        flags: --linelength=120
        filter: -whitespace/tab

    - name: cppcheck
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ runner.workspace }}/otservbr-global
        cppcheck --version
        $HOME/bin/reviewdog -reporter=github-pr-check -runners=cppcheck

    - name: luacheck
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        luacheck --version
        cd ${{ runner.workspace }}/otservbr-global
        $HOME/bin/reviewdog -reporter=github-pr-check -runners=luacheck

    - name: luac
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ runner.workspace }}/otservbr-global
        luac -v
        $HOME/bin/reviewdog -reporter=github-pr-check -runners=luac

    - name: xmllint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ runner.workspace }}/otservbr-global
        xmllint --version
        $HOME/bin/reviewdog -reporter=github-pr-check -runners=xmllint
